#include "stdrom.h"
#include "string.h"
#include "define.h"
#include "libc.h"
#include "l_libc.h"

#include "globalevariablen.h"
#include "prototypen.h"
#include "knack.h"
#include "randomg.h"
#include "testdot.h"
#include "playai.h"
#include "graphics.h"
#include "testbutton.h"
#include "leverpush.h"
#include "cls.h"
#include "displaysetup.h"
#include "sound.h"
