#Makefile for PocketViewer2 Sample Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = PocketPong

#== Program Name ==
PROGNAME = "PocketPong"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\xxx.obj \
		$(ODIR)\leverpush.obj

#== IncludeHeaderFile ==
#HEADFILE = 	$(HDIR)\ponix.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

