#Makefile for PocketViewer2 Sample Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = MakeDat

#== Program Name ==
PROGNAME = "MakeData"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0204

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\Icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS = $(ODIR)\MakeDat.obj \
          $(ODIR)\input.obj

#== IncludeHeaderFile ==
HEADFILE = $(HDIR)\input.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2
