#Makefile for Mathe Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Mathe

#== Program Name ==
PROGNAME = "Mathe"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0101

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\Mathe.obj  

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\Mathe.h  

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

