#Makefile for PocketViewer Sample Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = sound

#== Program Name ==
PROGNAME = "sound"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0010

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\sound.obj  \

#== IncludeHeaderFile ==
HEADFILE = 	

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

