#Makefile for LodeRuner

include $(PVC)\COM_LNK\MakeSDK.1

TARGET = PVRunner

PROGNAME = "PVRunner"

VERSION = 0152

MICON = menuicon\icon.bmp

LICON = menuicon\Licon.bmp

APLOBJS =	$(ODIR)\LodeRuner.obj \
                $(ODIR)\lever.obj

include $(PVC)\COM_LNK\MakeSDK.2

