#Makefile for PocketViewer2 Sample Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = pvtron

#== Program Name ==
PROGNAME = "PVTron"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0120

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\pvtron.obj \
		$(OBJ)\leverpush.obj

#== IncludeHeaderFile ==
HEADFILE = 	

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

