#Makefile for MAd

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Kassenbuch

#== Program Name ==
PROGNAME = "Kassenbuch"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\Kassenbuch_3.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Kassenbuch_3.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\MAd.obj \

#== IncludeHeaderFile ==
HEADFILE = 	

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

