#Makefile for PocketViewer2 Sample Program

include ..\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = sample

#== Program Name ==
PROGNAME = "Sample"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\sample.obj  \
		$(ODIR)\sample2.obj

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\sample.h

### ----------------------------------------- ###

include ..\COM_LNK\MakeSDK.2

