#Makefile for PocketViewer2 PalmFontEx Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = PalmFontEx

#== Program Name ==
PROGNAME = "PalmFontEx"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\palmfontex.obj \
		$(ODIR)\palmfont.obj \
		$(ODIR)\squaredance_ro_pdb.obj \
		$(ODIR)\alpha_ro.obj

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\palmfont.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

