#Makefile for PocketViewer2 Battle Ship

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Battle

#== Program Name ==
PROGNAME = "Battle Ship"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\battle.obj  \
		$(ODIR)\btlboard.obj\
		$(ODIR)\btldata.obj \
		$(ODIR)\btlmisc.obj \
		$(ODIR)\btlset.obj \
		$(ODIR)\btllang.obj 		

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\battle.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2
