#Makefile for PocketViewer "Maze"

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Maze

#== Program Name ==
PROGNAME = "Maze"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\soundlib.obj \
		$(ODIR)\maze.obj

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\soundlib.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

