#Makefile for a PocketViewer2 Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = viewicon

#== Program Name ==
PROGNAME = "ViewIcon"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0010

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\siicon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\silicon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\viewicon.obj				

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\viewicon.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

