#Makefile for PocketViewer2 Sample Program

include ..\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = periodic

#== Program Name ==
PROGNAME = "Periodic"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0107

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\periodic.obj  \
		

#== IncludeHeaderFile ==


### ----------------------------------------- ###

include ..\COM_LNK\MakeSDK.2
