#Makefile for PocketViewer2 Sample Program

include $(PVC)\com_lnk\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Ataxx

#== Program Name ==
PROGNAME = "Ataxx"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0102

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\ataxx.obj \
		$(ODIR)\ataxxrc.obj

#== IncludeHeaderFile ==
HEADFILE =

### ----------------------------------------- ###

include $(PVC)\com_lnk\MakeSDK.2

