#Makefile for PocketViewer2 Sample Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = zahlenraten

#== Program Name ==
PROGNAME = "Zahlenraten"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0200

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\zahlenraten.obj 

#== IncludeHeaderFile ==
HEADFILE = 	

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

