#Makefile for PocketViewer GetOS Program

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = GetOS2

#== Program Name ==
PROGNAME = "GetOS2"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0120

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\GetOS.obj $(ODIR)\sx.obj

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\sx.h $(HDIR)\crcxm.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

