#Makefile for PocketViewer2 Escoba

include ..\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Escoba

#== Program Name ==
PROGNAME = "Escoba"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0110

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =$(ODIR)\Escoba.obj  \
         $(ODIR)\EscData.obj \
         $(ODIR)\EscGraph.obj \
         $(ODIR)\EscMisc.obj \
         $(ODIR)\EscLang.obj \
         
#== IncludeHeaderFile ==
HEADFILE =  $(HDIR)\escoba.h

### ----------------------------------------- ###

include ..\COM_LNK\MakeSDK.2
