#Makefile for PocketViewer Sample Program

include ..\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = Puzzle

#== Program Name ==
PROGNAME = "Puzzle"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0100

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\puzzle.obj  \
		$(ODIR)\gdata.obj

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\puzzle.h \
		$(HDIR)\gdata.h

### ----------------------------------------- ###

include ..\COM_LNK\MakeSDK.2

