name: My Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make
      working-directory: ./Source/Apps/AssTest
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Ataxx
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Autostart
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/BallLine
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Battle
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/BattStat
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/BlackJak
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Chimpa
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Collection
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Domino
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Dumper
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Escoba
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Filemanager
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/FileSave
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/GetOS2
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/HelloWorld
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/IScratch
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Kassenbuch
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/LateSave
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/MakeDat2
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Mathe
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Maze
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Metronom
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PalmFontEx
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Periodic
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PermLight
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PocketPong
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PPlot
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PVMail
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PVRunner
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PVTetris
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PVToday
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PVTron
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/ReplMenu
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Sample
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Sample1
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Sound
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/SoundLib
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/TestApp
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/ViewIcon
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Zahlenraten
      run: .\mk.bat

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: All binary results
        path: ./Source/Apps/User_Bin

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: All assembler results
        path: ./Source/Apps/Obj
  