name: My Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make
      working-directory: ./Source/Apps/Sample
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Sample1
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/GetOS2
      run: .\mk.bat

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: All binary results
        path: ./Source/Apps/Bin
