name: My Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make
      working-directory: ./Source/Apps/Ataxx
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Autostart
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/BattStat
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/BlackJak
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/FileSave
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/GetOS2
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/LateSave
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/MakeDat2
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Metronom
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PalmFontEx
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/PermLight
      run: .\mk.bat
      
    - name: Make
      working-directory: ./Source/Apps/PVMail
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/ReplMenu
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Sample
      run: .\mk.bat

    - name: Make
      working-directory: ./Source/Apps/Sample1
      run: .\mk.bat

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: All binary results
        path: ./Source/Apps/Bin
