#Makefile for PocketViewer "SoundLib"

include $(PVC)\COM_LNK\MakeSDK.1

### -------- Define Make Application -------- ###

#== TargetName ==
TARGET  = TestSound

#== Program Name ==
PROGNAME = "TestSound"

#== ProgramVersion(EX. 0100->Ver1.00) ==
VERSION = 0001

#== MenuIcon (Xsize=45dot,Ysize=28dot) ==
MICON = menuicon\icon.bmp

#== ListMenuIcon (Xsize=27dot,Ysize=20dot) ==
LICON = menuicon\Licon.bmp

#== CompileObjectFile ==
APLOBJS =	$(ODIR)\soundlib.obj \
	        $(ODIR)\test4.obj

#== IncludeHeaderFile ==
HEADFILE = 	$(HDIR)\soundlib.h

### ----------------------------------------- ###

include $(PVC)\COM_LNK\MakeSDK.2

